Fix for id:000002, id:000207: allocation-size-too-big in kaitai read_bytes
The read_bytes function allocates a vector of the requested size before checking
if the stream actually has that many bytes available. Malformed firmware can
cause the Kaitai parser to request multi-exabyte allocations. Add a stream
bounds check before the allocation to throw early on invalid sizes.

Crash report (id:000002,sig:06,sync:master,src:005710):
---
ERROR: AddressSanitizer: requested allocation size 0x4ffa6900fffffe00 exceeds maximum supported size of 0x10000000000 (thread T0)
    #0 in operator new(unsigned long)
    #7 in kaitai::kstream::read_bytes kaitaistream.cpp:481
    #8 in edk2_ftw_t::_read() edk2_ftw.cpp:32
    #10 in NvramParser::parseNvramVolumeBody nvramparser.cpp:758
---

Crash report (id:000207,sig:06):
---
ERROR: AddressSanitizer: requested allocation size 0x4853414c465f0010 exceeds maximum supported size of 0x10000000000 (thread T0)
    #0 in operator new(unsigned long)
    #7 in kaitai::kstream::read_bytes kaitaistream.cpp:481
    #8 in edk2_ftw_t::_read() edk2_ftw.cpp:32
    #10 in NvramParser::parseNvramVolumeBody nvramparser.cpp:758
---